//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Updates_tbl
    {
        public int updatesId { get; set; }
        public int codeStore { get; set; }
        public int codeWorker { get; set; }
        public System.DateTime dateVisit { get; set; }
        public Nullable<System.TimeSpan> begginingTime { get; set; }
        public Nullable<System.TimeSpan> exitingTime { get; set; }
        public string remarks { get; set; }
        public Nullable<int> result { get; set; }
    
        public virtual Store_tbl Store_tbl { get; set; }
        public virtual Worker_tbl Worker_tbl { get; set; }
    }
}
