//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_tbl
    {
        public int userId { get; set; }
        public string userUserName { get; set; }
        public string userPassword { get; set; }
        public int userRole { get; set; }
    }
}
